name: Build and Sign

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up keychain and import certificate
      run: |
        # Decode the base64 certificate stored in CERTIFICATE_P12 and save it as developer_certificate.p12
        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12

        # Check if the certificate file is valid
        if [ -s developer_certificate.p12 ]; then
          echo "Certificate file is valid."
        else
          echo "Certificate file is invalid or empty."
          exit 1
        fi
        
        # Unlock the keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" /Users/runner/Library/Keychains/login.keychain-db
        
        # Import the developer_certificate.p12 into the keychain
        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "$P12_PASSWORD" -T /usr/bin/codesign
        
        # Set keychain settings and access permissions
        security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain-db
        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" /Users/runner/Library/Keychains/login.keychain-db
        
        # Clean up the certificate file
        rm developer_certificate.p12
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

    # Continue with build, sign, and deploy steps...
