name: SherlockElf

on:
  workflow_dispatch:
  push:
    branches: ["main", "ci"]

permissions:
  contents: write

jobs:
  ios_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Decode the base64 certificate and save it as developer_certificate.p12
      run: |
        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
        if [ ! -s developer_certificate.p12 ]; then
          echo "Certificate file is invalid or empty."
          exit 1
        else
          echo "Certificate file is valid."
        fi

    - name: Test import the certificate into keychain
      run: |
        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed, possibly due to incorrect password."

    - name: Exit if import fails
      if: failure()
      run: exit 1

    - name: Continue with build process if import succeeds
      shell: bash
      run: |
        echo "Proceeding with the build process as the certificate was imported successfully."
        # Weitere Build-Schritte hier

