name: SherlockElf

on:
  workflow_dispatch:
  push:
    branches: ["main", "ci"]

permissions:
  contents: write

jobs:
  ios_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Set IOS_CERTID environment variable
      run: echo "IOS_CERTID=${{ secrets.IOS_CERTID }}" >> $GITHUB_ENV

    - name: Decode the base64 certificate and save it as developer_certificate.p12
      run: |
        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
        if [ ! -s developer_certificate.p12 ]; then
          echo "Certificate file is invalid or empty."
          exit 1
        else
          echo "Certificate file is valid."
        fi

    - name: Import the certificate into keychain
      run: |
        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed, possibly due to incorrect password."

    - name: Exit if import fails
      if: failure()
      run: exit 1

    - name: Clone Frida repository with submodules
      run: |
        git clone --recurse-submodules https://github.com/frida/frida
        cd frida
        git submodule update --init --recursive

    - name: Apply patches to frida-core
      shell: bash
      run: |
        if [ -d "frida/subprojects/frida-core" ]; then
          cd frida/subprojects/frida-core
          for patch in ${{ github.workspace }}/patches/frida-core/*.patch; do
            git am "$patch"
          done
        else
          echo "Directory frida/subprojects/frida-core does not exist"
          exit 1
        fi

    - name: Build Frida Gadget and Frida Server for iOS
      shell: bash
      run: |
        export PATH=$PATH:/Users/runner/work/SherlockElf/SherlockElf/frida/deps/toolchain-macos-arm64/bin
        mkdir -p build-ios-arm64
        cd build-ios-arm64
        ../frida/configure --host=ios-arm64
        ninja subprojects/frida-core/lib/gadget/frida-gadget.dylib subprojects/frida-core/server/frida-server || { echo "Build failed for ios-arm64"; ls -alh; exit 1; }

    - name: Package Frida Gadget and Frida Server for iOS
      shell: bash
      run: |
        gzip build-ios-arm64/subprojects/frida-core/lib/gadget/frida-gadget.dylib
        gzip build-ios-arm64/subprojects/frida-core/server/frida-server

    - name: Upload iOS arm64 Frida Gadget for SherlockElf
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/lib/gadget/frida-gadget.dylib.gz
        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.dylib.gz
        asset_content_type: application/octet-stream

    - name: Upload iOS arm64 Frida Server for SherlockElf
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/server/frida-server.gz
        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.gz
        asset_content_type: application/octet-stream
